name: Build Plugin Container

on:
  pull_request:
    paths:
    - 'plugins/headlamp-plugin/**'
    - '.github/workflows/plugin-container.yml'
  push:
    branches:
      - main
      - rc-*
      - testing-rc-*
    paths:
    - 'plugins/headlamp-plugin/**'
    - '.github/workflows/plugin-container.yml'

permissions:
  contents: read
  security-events: write # required for uploading security scan results

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

    - name: Build plugin container
      uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4.2.1
      with:
        context: plugins/headlamp-plugin
        file: plugins/headlamp-plugin/Dockerfile
        push: false
        tags: ghcr.io/headlamp-k8s/headlamp-plugin:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        # Add output for local image scanning
        outputs: type=docker,dest=/tmp/headlamp-plugin.tar

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        input: /tmp/headlamp-plugin.tar
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'
        ignore-unfixed: true

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Test plugin container
      run: |
        # Create test directories
        mkdir -p test/plugins test/config
        
        # Create a test config file
        cat > test/config/config.yaml <<EOF
        plugins:
          - name: test-appcatalog
            version: 0.0.1
            repository: https://artifacthub.io/packages/headlamp/test-123/appcatalog_headlamp_plugin
        EOF

        # Run the container with test config
        docker run --rm \
          -v $(pwd)/test/plugins:/plugins-dir \
          -v $(pwd)/test/config/config.yaml:/plugins.yaml \
          ghcr.io/headlamp-k8s/headlamp-plugin:test \
          install --config /plugins.yaml --folderName /plugins-dir