name: Build Plugin Container

on:
  pull_request:
    paths:
    - 'plugins/headlamp-plugin/**'
    - '.github/workflows/plugin-container.yml'
  push:
    branches:
      - main
      - test_workflow
      - rc-*
      - testing-rc-*
    paths:
    - 'plugins/headlamp-plugin/**'
    - '.github/workflows/plugin-container.yml'

permissions:
  contents: read
  security-events: write # required for uploading security scan results

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

    - name: Build plugin container
      uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4.2.1
      with:
        context: plugins/headlamp-plugin
        file: plugins/headlamp-plugin/Dockerfile
        push: false
        tags: ghcr.io/headlamp-k8s/headlamp-plugin:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        # Add output for local image scanning
        outputs: type=docker,dest=/tmp/headlamp-plugin.tar

    # Setup Trivy
    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.47.0

    # Run vulnerability scan
    - name: Run Trivy vulnerability scanner
      continue-on-error: true
      id: scan
      run: |
        # First update Trivy DB
        trivy image --download-db-only
        
        # Run the scan and store output
        set +e
        trivy image \
          --input /tmp/headlamp-plugin.tar \
          --format sarif \
          --output trivy-results.sarif \
          --severity HIGH,CRITICAL \
          --ignore-unfixed \
          --exit-code 1
        
        echo "SCAN_EXIT_CODE=$?" >> $GITHUB_ENV
        set -e

    - name: Upload Trivy scan results to GitHub Security tab
      if: always() && steps.scan.outcome == 'success'
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Check scan results
      if: env.SCAN_EXIT_CODE == 1
      run: |
        echo "Security vulnerabilities were found. Check the scan results for details."
        exit 1
